### ISSUE TITLE
Allow to use patches

### ISSUE THREAD

**Issue by evgeniysergeev** [OpenRA/d2#117]
d2 mod based on particular engine. (engine-20190314 at this moment)
Some issues can not be fixed in mod and need changes in engine.
Such issues marked 'waiting for upstream'.
Add directory ./patches with patches to current used engine, that will allow to modify engine after downloading. This will allow to not wait for next release, or release+1 or longer until needed changes will be in official engine.
this ./patches directory need to be reviewed on each engine change.

**Comment by GraionDilach** [comment]
The SDK allows to use custom engine sources. You're able to just run a branch in say evgeniysergeev/OpenRA and setup the mod against a branch in that repo.

Just adapt https://github.com/OpenRA/d2/blob/master/mod.config#L109 pretty much.

**Comment by evgeniysergeev** [comment]
Thanks. Looks like using patches not needed then.
