### ISSUE TITLE
Starting Cash

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/d2#12]
from all missions : 

A1 1000 ...H1 1000 ...O1 1000
A2 1200 ...H2 1200 ...O2 1200
A3 1500 ...H3 1500 ...O3 1500
A4 1500 ...H4 1500 ...O4 1500
A5 1500 ...H5 1500 ...O5 1500
A6 1800 ...H6 1700 ...O6 1700
A7 1800 ...H7 2000 ...O7 2000
A8 2000 ...H8 2000 ...O8 2000
A9 1000 ...H9 1000 ...O9 1500

based off of these values ... i would like to have following options for starting money : 

1000
1500 - Default
2000

along with establishing all buildings and units original costs .. and harvester-behaviour ... this starting-money should provide us with enough ressources for a slow-paced but steady buildup (on normal gamespeed)

**Comment by evgeniysergeev** [comment]
in 8be05bc0b4eeee185543dde17692b73ed05fc7c1

**Comment by Micr0Bit** [comment]
@evgeniysergeev : could you please join the irc ? so i can give you the files i have changed so far ... with the original costs
