### ISSUE TITLE
Import original maps

### ISSUE THREAD

**Issue by evgeniysergeev** [OpenRA/d2#129]
Do not hold imported maps, but create import function that imports originals maps at first game launch.

**Comment by TheRaffy** [comment]
Good thought. That might make the sd2 maps also importable. 👍  
https://www.moddb.com/mods/super-dune-ii-classic

**Comment by evgeniysergeev** [comment]
> Good thought. That might make the sd2 maps also importable. 👍
> https://www.moddb.com/mods/super-dune-ii-classic

The main idea is to not store original maps here. For sd2 it will be better to create utility command to convert them to openra format

**Comment by evgeniysergeev** [comment]
waiting for #131
