### ISSUE TITLE
Build fails for some, likely due to the imprudent versioning of the engine

### ISSUE THREAD

**Issue by fusion809** [OpenRA/d2#145]
Hi,

The engine used for this mod is one from midway during the toolchain overhaul, and for some the build of it is failing on Arch Linux (not all, however, as for me the build goes fine). I maintain the [openra-d2-git AUR package](https://aur.archlinux.org/pkgbase/openra-d2-git/), and here is the paste shared by someone experiencing a build failure that occurs around the stage of downloading the engine: https://pastebin.com/ENUHKgkr. Could you please find a fix for this issue?

Thanks for your time

**Comment by pchote** [comment]
Updating to the new Mod SDK release and playtest engine should fix this.

**Comment by evgeniysergeev** [comment]
Hello @fusion809,
Is this reporduced after updating to playtest-20190825 ?

**Comment by fusion809** [comment]
I'm not the one that experiences this error, I just left a message to the person that first reported this issue at the AUR, https://aur.archlinux.org/packages/openra-d2-git/#comment-709665. Hoping they'll see the comment and respond.

**Comment by evgeniysergeev** [comment]
Is this still actual issue?

**Comment by fusion809** [comment]
Nope.
