### ISSUE TITLE
Remove crates and ranks from d2 

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/d2#2]
talked about this with @x-a-n-a-x on Irc ... 

neither of them fit into our dune2 mod ... first of all , we dont have proper dune2-crates (nor do they exist in the original) ... and the ranks look aweful and oversized (also didnt exist in the original)

**Comment by x-a-n-a-x** [comment]
I agree with @Micr0Bit.
I don't like much the idea to have crates and ranks in our Dune 2 mod.

**Comment by evgeniysergeev** [comment]
remove crates in 345408bfbaada953e7d45a926d4c3ee49838ddd2

**Comment by Micr0Bit** [comment]
@evgeniysergeev : awesome , thx !
