### ISSUE TITLE
can't access wiki

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/d2#27]
would like to add information about dune2 ... but i only get directed to OpenRA/d2

**Comment by tatey** [comment]
Would be nice to link to http://www.abandonia.com/en/games/36/Dune+II+-+The+Building+of+a+Dynasty.html in the wiki where you can find the original *.PAK files.

**Comment by Micr0Bit** [comment]
https://github.com/OpenRA/d2/wiki
