### ISSUE TITLE
Harvesting animation polluted

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/d2#37]
![harvsdirty](https://cloud.githubusercontent.com/assets/9139965/24034104/40c84fd2-0af0-11e7-8b8d-86a7451f4419.png)

the left one is our current animation ... this obviously doesnt look like the original animation (right one)

**Comment by Micr0Bit** [comment]
c6be808 indeed fixed this ... but i've noticed that there is still a flickering in the animation 

as if there is an empty frame that is visible for a split-second during the animation-loop

**Comment by evgeniysergeev** [comment]
should be already fixed
