### ISSUE TITLE
Implement a reduced sight when moving for all units

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/d2#40]
In the original Dune2 all units had reduced sight to 1 cell when moving
@MustaphaTR : thx for the tip

![quadreduced](https://cloud.githubusercontent.com/assets/9139965/24083546/19381e58-0cd9-11e7-8a8e-450b92e6489f.png)

**Comment by MustaphaTR** [comment]
We already have a [GrantConditionOnMovement](https://github.com/OpenRA/OpenRA/wiki/Traits-(playtest)#grantconditiononmovement) trait. As RevealsShourd is conditional since the Gap Gen. changes, this should be possible to do.

**Comment by Micr0Bit** [comment]
6f05e2
