### ISSUE TITLE
Use the mod template project

### ISSUE THREAD

**Issue by Phrohdoh** [OpenRA/d2#41]
https://github.com/OpenRA/OpenRAModTemplate

~~https://github.com/Phrohdoh/openra-ra2-standalone is a _temporary_ example of this.~~

**Update**: See [OpenRA/RA2](https://github.com/OpenRA/ra2)

**Comment by Mailaender** [comment]
https://github.com/OpenRA/ra2 officially made the switch in https://github.com/OpenRA/ra2/pull/386.

**Comment by evgeniysergeev** [comment]
https://github.com/OpenRA/d2/issues/56
