### ISSUE TITLE
Worms spawn under rock-tiles

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/d2#42]
I've noticed that when my units started to shoot on specific rock-tiles ... and i've heard the worms electrostatic-sounds but couldnt find him anywhere

![electro](https://cloud.githubusercontent.com/assets/9139965/24286526/df55bac4-1075-11e7-93ad-2c83a5e39d3d.png)

**Comment by abcdefg30** [comment]
Fixed in https://github.com/OpenRA/d2/commit/327733a469cd63017979b369dd67b7aef72bab5f.
