### ISSUE TITLE
Roland MT-32?

### ISSUE THREAD

**Issue by TheRaffy** [OpenRA/d2#53]
Hey, what do you guys think about the midi module / soundcard? 
Shall this mod use the adlib/soundblaster or try to emulate the legendary Roland MT-32 ?

Some history lesson for the younger generation.
https://www.youtube.com/watch?v=BMmFcs-_4x4
https://www.youtube.com/watch?v=kQADZeB-z8M
https://sourceforge.net/projects/munt/

**Comment by Walkman100** [comment]
As awesome as that would be (love those vids btw), I think it's unlikely because of the changes needed to the engine

**Comment by TheRaffy** [comment]
The original tunes are .mid files. -> not yet supported -> means changes are required anyway.

**Comment by Unit158** [comment]
There are two ways to do it:
Keep the implementation clean and simple, just render the midi files to a wav or ogg (someday).
Write a bunch of really annoying code to implement a midi-synth, or add another dependency.

Personally I think the former would be a more efficient approach.

**Comment by TheRaffy** [comment]
For recording we could use this https://www.youtube.com/watch?v=j_5RWxHHVvE as an alternative to the real Hardware. ( I don't own a MT-32, and think noboy else arround here does either)

But I just understood, that "munt" needs MT-32 Roms and I assume other emulator libs will need some too. I tought they are some kind of included, welll this speaks against some implementation of an  mt-32 emulatior  into this mod.

So In my opinion an implementation of any Midi lib would be better than shipping any records.
simply because of the file size, and other modes to come, for example warcraft I also uses midis, (as far as I know http://speakersoundtracks.tk/soundtracks/wc1/mid/ ) But out of curiousity what file format does RA and TD use?
 
Sometimes any solution is better than none (first come fist serve)
