### ISSUE TITLE
Migrate to the OpenRA Mod SDK

### ISSUE THREAD

**Issue by pchote** [OpenRA/d2#56]
Modifying the base OpenRA code directly is no longer supported - we now provide a [modding SDK](https://github.com/OpenRA/OpenRAModSDK) that makes it much easier for your players/testers to compile and run custom mods.

**Comment by Blakeley00** [comment]
I was just about to post asking you guys about this. New release with the mod chooser dropped and better mod support is out. Looking forward to you guys releasing a new easy to install version of your mod for this new openra!

Then I can show it to the all folks asking "how how how??" on my Dune 2 videos lol.

**Comment by SteamsDev** [comment]
I'm beginning to think this mod is dead. I might combine the two repositories and see if I can get a working Dune 2 mod SDK. I'll create a new repository if I do.

**Comment by Blakeley00** [comment]
Yeah it's not looking good here. Good luck mate, hope it goes well!!!

**Comment by evgeniysergeev** [comment]
done in https://github.com/OpenRA/d2/pull/57
