### ISSUE TITLE
D2RevealsShroud trait works incorrectly

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/d2#60]
Same behaviour can be achieved using GrantConditionOnMovement and multlipile RevealsShroud traits.

**Comment by evgeniysergeev** [comment]
Initially RevealsShroud and movement was used for that. But during long walk, units stops and without D2RevealsShroud it looks not good. it looks like a line with circles, but D2RevealsShroud skip this small stops during long movement and removed shroud looks like in original.

**Comment by MustaphaTR** [comment]
This is still wrong. Harvesters while harvesting, and units while firing use the movement range too. Not sure about harvesting, but firing units shouldn't get the range nerf.
