### ISSUE TITLE
Dune 2 should have per building queues.

### ISSUE THREAD

**Issue by MustaphaTR** [OpenRA/d2#77]
There are 2 things we can do,

1. Get a new UI that looks like TD mod's one (or just use TD UI) and use the handling TD has.

2. As i do on Generals Alpha, stick to D2k UI. Remove the queue buttons, Require selection of the structures on the map to get the queues.

2nd sounds more like original, so i would go with that. But wanted to ask to get opinion.

**Comment by Micr0Bit** [comment]
2nd sounds also very good to me , and a positive effect of it is that it adds to gameplay-difference from out typical openra-mods.

2 additional things ... the was no actually queue at all in the original ... you would have to click the building icon everytime you want another unit or building ... this is a key-oldschool feature ... we should consider that

second ... i am still heavily in favor of changing the UI in terms of the graphics "and" functions towards the original , but i know this really is our last concern at the moment , still we should keep that thought in our heads for the future

so, "yes" for :

2. As i do on Generals Alpha, stick to D2k UI. Remove the queue buttons, Require selection of the structures on the map to get the queues.

**Comment by MustaphaTR** [comment]
I know that original didn't have queueing, and removing the queueing also is possible on bleed version of the engine, but not the lastest release which d2 mod is on. We can do that after another release hits, if we wanna stick with release versions.

**Comment by evgeniysergeev** [comment]
I like queueing. it's a mod that looks like original, but with new features.

**Comment by TheRaffy** [comment]
Hey, im very glad this mod is getting some momentum again! Much thanks for that.
Great work, Plz keep it up!  Im watching every step.
Btw. I also like queueing!

I still have the opinion that adding new features to old games is the best you can do with them. Like Multiplayer :)  but hornestly adding new Features to old games is making them interesting again and means increasing the userfriendlyness. That will attract players from yonger generations and therefore the games will have a bigger userbase.

**Comment by dderevjanik** [comment]
@TheRaffy Yes, new gameplay features for d2 would be great ! For example, there's d2 clone Dune 2 Golden Path, where they introduced a several gameplay improvments. 

- You can place several pavements at once
- You can build simultaneously several buildings
- Pavements are automatically placed near you CY after you upgrade it.
- Rafineries automatically rebuild ore truck when one is destroyed

- Ore truck has gun attached
- Research that automatically repairs buildings
- You can airlift any unit (similar to C&C3)

- When sand storm occurs it will hide revealed parts of map
- Retreat function. When unit is below % health, it will automatically retreat to `retreat point`
