### ISSUE TITLE
Add command-buttons

### ISSUE THREAD

**Issue by Micr0Bit** [OpenRA/d2#8]
important features that makes Dune2 what it actually was ... and is a huge difference from other titles such dune2000's , tiberian dawn's and red alert's "multi-selection" and "mouse-commands"

this would be an actually "privilege" for Dune2 to have , a feature

![command](https://cloud.githubusercontent.com/assets/9139965/26757454/efdd3e16-48bb-11e7-90da-25ef5e8166a3.jpg)

**Comment by x-a-n-a-x** [comment]
But could we have them as options ? (I mean, multi-selection and mouse-commands)

**Comment by Micr0Bit** [comment]
if i wanted to play dune with a multi-selection and mouse-commands i could just play dune2000 ... 

but i guess an option wont hurt

**Comment by Micr0Bit** [comment]
https://github.com/OpenRA/OpenRA/pull/13442 will be the answer to that, once its properly tested

**Comment by xan2622** [comment]
***Microbit > if i wanted to play dune with a multi-selection and mouse-commands i could just play dune2000***
That's a good point.
