### ISSUE TITLE
sharing cleaned d2 sounds

### ISSUE THREAD

**Issue by TheRaffy** [OpenRA/d2#88]
Hey,
I once cleaned up the sounds of d2. 
The original soudns have a lot clicking, because files start and end suddently, when the wave is not at the zero level.
So maybe this will make the audio more enjoyable. 
[dune2 Sound cleaning.zip](https://github.com/OpenRA/d2/files/2021848/dune2.Sound.cleaning.zip)

**Comment by evgeniysergeev** [comment]
this mod reads and use original data files.

**Comment by evgeniysergeev** [comment]
d2 mod should be VERY close to original game. some enhancements possible but not in assets. not in sounds or images. this was original idea of d2 mod

**Comment by TheRaffy** [comment]
This could also be done technically by fading in and out the first milliseconds.

**Comment by evgeniysergeev** [comment]
edited for remove zip with possibly copyrighted assets
