### ISSUE TITLE
D2VocLoader should be called VocLoader

### ISSUE THREAD

**Issue by IceReaper** [OpenRA/d2#89]
D2VocLoader should be called VocLoader because its not a dune2 specific format. Its actualy a standard Creative VOC format multiple old rts use (example: Warcraft 1), and it might be a good thing to have this decoupled from D2 branding.

**Comment by evgeniysergeev** [comment]
OpenRA already have VocLoader, but it is not working.
After that pull request will be merged, https://github.com/OpenRA/OpenRA/pull/15975,
it will be possible to remove D2VocLoader completelly
